# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src/prayer/__main__.py'],
    pathex=['src'],
    binaries=[],
    datas=[('src/prayer/assets', 'prayer/assets'), ('src/prayer/config', 'prayer/config')],
    hiddenimports=[
        'prayer.auth', 
        'prayer.calendar_api', 
        'prayer.config', 
        'prayer.platform', 
        'prayer.gui', 
        'prayer.state', 
        'prayer.tray_icon',
        'json',
        'argcomplete',
        'zoneinfo',
        'appdirs',
        'prayer.scheduler',
        'prayer.actions',
        'prayer.platform.service',
        'APScheduler',
        'python_vlc',
        'keyring',
        'tzlocal',
        'pystray',
        'PySide6.QtSvg',
        'PySide6.QtNetwork',
        'PySide6.QtWidgets',
        'requests',
        'ics',
        'schedule',
        'google_api_python_client',
        'google_auth_httplib2',
        'google_auth_oauthlib',
        'msgraph_sdk',
        'playsound',
        'PySide6',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PrayerPlayer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

app = BUNDLE(
    exe,
    name='PrayerPlayer.app',
    icon='src/prayer/assets/mosque.png',
    bundle_identifier=None,
)
