# Reusable workflow for common Python application build steps
name: Build Common Python App

on: 
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python_version:
        required: true
        type: string
    
    secrets:
      GOOGLE_CLIENT_CONFIG_JSON:
        required: true
      TOKEN:
        required: true

jobs:
  build-common:
    runs-on: ${{ inputs.os }}
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Linux GUI dependencies
      if: ${{ inputs.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1 libpulse0 libxcb-cursor0 libasound2-dev

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Create Google Client Config from secret
      run: echo "${{ secrets.GOOGLE_CLIENT_CONFIG_JSON }}" > src/config/security/google_client_config.json

    - name: Build application executable
      run: |
        pyinstaller --noconfirm PrayerPlayer.spec

    - name: List dist directory
      run: ls -R dist/

    - name: Upload application executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: prayer-player-${{ inputs.os }}-executable
        path: dist/

    
