# A unique name for the workflow.
name: Build and Release Prayer Player (macOS)

# Triggers the workflow on push or pull request events for the main branch.
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      os: macos-latest
      python_version: '3.10'
    secrets:
      GOOGLE_CLIENT_CONFIG_JSON: ${{ secrets.GOOGLE_CLIENT_CONFIG_JSON }}
      TOKEN: ${{ secrets.TOKEN }}

  test:
    needs: build
    uses: ./.github/workflows/test-dry-run.yml
    with:
      os: macos-latest
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  package-dmg:
    runs-on: macos-latest
    needs: test
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Download application executable artifact
      uses: actions/download-artifact@v4
      with:
        name: prayer-player-macos-latest-executable
        path: dist

    - name: Build and package macOS .dmg file
      shell: bash
      run: |
        # Install create-dmg tool using Homebrew.
        brew install create-dmg

        # Create the final .dmg installer.
        mv dist/PrayerPlayer.app dist/
        create-dmg \
          --volname "PrayerPlayer Installer" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "PrayerPlayer.app" 200 190 \
          --hide-extension "PrayerPlayer.app" \
          --app-drop-link 600 185 \
          "dist/PrayerPlayer.dmg" \
          "dist/PrayerPlayer.app"

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prayer-player-macos
        path: dist/*.dmg
