# A unique name for the workflow.
name: Build and Release Prayer Player (Ubuntu)

# Triggers the workflow on push or pull request events for the main branch.
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      os: ubuntu-22.04
      python_version: '3.10'
    secrets:
      GOOGLE_CLIENT_CONFIG_JSON: ${{ secrets.GOOGLE_CLIENT_CONFIG_JSON }}
      TOKEN: ${{ secrets.TOKEN }}

  package-deb:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Download application executable artifact
      uses: actions/download-artifact@v4
      with:
        name: prayer-player-ubuntu-22.04-executable
        path: dist

    - name: Build and package Ubuntu .deb file
      shell: bash
      run: |
          # Exit immediately if a command fails.
          set -e

          # Define package details
          DEB_DIR="prayer-player-deb"
          VERSION=$(python -c "from src.__version__ import __version__; print(__version__)")

          # Create the Debian package structure
          mkdir -p "${DEB_DIR}/DEBIAN"
          mkdir -p "${DEB_DIR}/usr/local/bin"
          mkdir -p "${DEB_DIR}/usr/share/applications"
          mkdir -p "${DEB_DIR}/usr/share/icons/hicolor/256x256/apps"

          # Create the control file using a heredoc for readability.
          cat <<EOF > "${DEB_DIR}/DEBIAN/control"
          Package: prayer-player
          Version: ${VERSION}
          Architecture: amd64
          Maintainer: Omar <dev@omar.com>
          Description: Prayer times application that plays the Adhan.
          EOF

          # Create the desktop entry file using a heredoc.
          cat <<EOF > "${DEB_DIR}/usr/share/applications/prayer-player.desktop"
          [Desktop Entry]
          Name=Prayer Player
          Exec=bash -c "/usr/local/bin/PrayerPlayer"
          Icon=prayer-player
          Type=Application;
          Categories=Utility;
          EOF

          # Copy the application executable and icon into the package structure.
          cp dist/PrayerPlayer "${DEB_DIR}/usr/local/bin/"
          cp src/assets/mosque.png "${DEB_DIR}/usr/share/icons/hicolor/256x256/apps/prayer-player.png"

          # Set correct permissions for the package directory.
          chmod -R 755 "${DEB_DIR}"

          # Build the final .deb package.
          dpkg-deb --build "${DEB_DIR}"

          # Move the created package to the dist folder for upload.
          mv "${DEB_DIR}.deb" "dist/prayer-player-${VERSION}-amd64.deb"

          # List the content of the dist folder to verify.
          echo "--- Final .deb artifact ---"
          ls -l dist/

    - name: Upload Ubuntu Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prayer-player-ubuntu
        path: dist/*.deb
