# A unique name for the workflow.
name: Build and Release Prayer Player (macOS)

# Triggers the workflow on push or pull request events for the main branch.
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    # This job runs on macOS to build for macOS.
    runs-on: macos-latest

    steps:
    # Step 1: Check out the repository code.
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up the specified Python version.
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install all required Python dependencies from requirements files.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    # Step 4: Build the application executable using PyInstaller.
    - name: Create Google Client Config from secret
      run: echo "${{ secrets.GOOGLE_CLIENT_CONFIG_JSON }}" > src/config/security/google_client_config.json

    - name: Create runtime temporary directory
      run: |
        mkdir -p /tmp/pyinstaller
        chmod 777 /tmp/pyinstaller

    - name: Build application executable
      run: pyinstaller --noconfirm PrayerPlayer.spec

    - name: Set up token for dry run
      run: |
        mkdir -p ~/Library/Application\ Support/PrayerPlayer
        echo "${{ secrets.TOKEN }}" > ~/Library/Application\ Support/PrayerPlayer/token.json

    # Step 5: Test application startup (dry run)
    - name: Test application startup (dry run)
      shell: bash
      run: |
        echo "Listing contents of dist directory:"
        ls -R dist
        echo "Running startup test for macOS"
        ./dist/PrayerPlayer --dry-run --country US --city "New York"

    # Step 6: Build and package macOS .dmg file
    - name: Build and package macOS .dmg file
      shell: bash
      run: |
        # Install create-dmg tool using Homebrew.
        brew install create-dmg

        # Create the final .dmg installer.
        create-dmg \
          --volname "PrayerPlayer Installer" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "PrayerPlayer.app" 200 190 \
          --hide-extension "PrayerPlayer.app" \
          --app-drop-link 600 185 \
          "dist/PrayerPlayer.dmg" \
          "dist/PrayerPlayer.app"

    # Step 7: Upload macOS Artifact
    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prayer-player-macos
        path: dist/*.dmg
