# A unique name for the workflow.
name: Build and Release Prayer Player (Windows)

# Triggers the workflow on push or pull request events for the main branch.
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      os: windows-latest
      python_version: '3.10'
    secrets:
      GOOGLE_CLIENT_CONFIG_JSON: ${{ secrets.GOOGLE_CLIENT_CONFIG_JSON }}
      TOKEN: ${{ secrets.TOKEN }}

  test:
    needs: build
    uses: ./.github/workflows/test-dry-run.yml
    with:
      os: windows-latest
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  package-exe:
    runs-on: windows-latest
    needs: test
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Download application executable artifact
      uses: actions/download-artifact@v4
      with:
        name: prayer-player-windows-executable
        path: dist

    - name: Install Inno Setup for Windows installer
      run: choco install innosetup --no-progress

    - name: Compile Windows installer
      run: iscc "deployment\windows\setup.iss"

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prayer-player-windows
        path: deployment/windows/Output/*.exe