# Reusable workflow for dry-run tests
name: Test Dry Run

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  test-dry-run:
    runs-on: ${{ inputs.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Download application executable artifact
      uses: actions/download-artifact@v4
      with:
        name: prayer-player-${{ inputs.os }}-executable
        path: dist

    - name: Set up token for dry run (macOS)
      if: runner.os == 'macOS'
      run: |
        mkdir -p ~/Library/Application\ Support/PrayerPlayer
        echo "${{ secrets.TOKEN }}" > ~/Library/Application\ Support/PrayerPlayer/token.json

    - name: Set up token for dry run (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir -p ~/.local/share/PrayerPlayer
        echo "${{ secrets.TOKEN }}" > ~/.local/share/PrayerPlayer/token.json

    - name: Set up token for dry run (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "$env:APPDATA\PrayerPlayer"
        Set-Content -Path "$env:APPDATA\PrayerPlayer\token.json" -Value "${{ secrets.TOKEN }}"

    - name: Make artifact executable
      if: runner.os != 'Windows'
      run: chmod +x dist/PrayerPlayer

    - name: Test application startup (dry run)
      shell: bash
      run: |
        echo "Listing contents of dist directory:"
        ls -R dist
        echo "Running startup test for ${{ inputs.os }}"
        # Adjust the executable path based on the OS
        if [ "${{ inputs.os }}" == "ubuntu-22.04" ]; then
          ./dist/PrayerPlayer/PrayerPlayer --dry-run --country US --city "New York"
        elif [ "${{ inputs.os }}" == "macos-latest" ]; then
          ./dist/PrayerPlayer.app/Contents/MacOS/PrayerPlayer --dry-run --country US --city "New York"
        elif [ "${{ inputs.os }}" == "windows-latest" ]; then
          ./dist/PrayerPlayer/PrayerPlayer.exe --dry-run --country US --city "New York"
        fi
